### ISSUE TITLE
This package is not work in Laravel 4.2？

### ISSUE THREAD

**Issue by hushulin** [bbrink68/Laracurl#1]
how i can use your Laracurl in my Lravel 4.2 ?

**Comment by ghost** [comment]
$fetchinfo = Laracurl::get('http://somewebsite.com/somepath');

**Comment by bbrink68** [comment]
Hello,
I've updated the package tags.  For Laravel 4.2 version:

    "mattbrown/laracurl": "1.0.0"

Use that in your composer.json.  Let me know if you have further issues after.

**Comment by bbrink68** [comment]
Closing this unless specific issues are reported.
