### ISSUE TITLE
Where is the version for 4.2 ?

### ISSUE THREAD

**Issue by ghost** [bbrink68/Laracurl#2]
i have added require...... into my composer.json and when I run composer update I got follwoing message

Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.16
    - Conclusion: don't install laravel/framework v4.2.15
    - Conclusion: don't install laravel/framework v4.2.14
    - Conclusion: don't install laravel/framework v4.2.13
    - Conclusion: don't install laravel/framework v4.2.12
    - Conclusion: don't install laravel/framework v4.2.11
    - Conclusion: don't install laravel/framework v4.2.10
    - Conclusion: don't install laravel/framework v4.2.9
    - Conclusion: don't install laravel/framework v4.2.8
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install laravel/framework v4.2.6
    - Conclusion: don't install laravel/framework v4.2.5
    - Conclusion: don't install laravel/framework v4.2.4
    - Conclusion: don't install laravel/framework v4.2.3
    - Installation request for mattbrown/laracurl dev-master -> satisfiable by mattbrown/laracurl[dev-master].
    - Conclusion: don't install laravel/framework v4.2.2
    - Conclusion: don't install laravel/framework v4.2.1
    - mattbrown/laracurl dev-master requires illuminate/support 5.\* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.22|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.4|don't install laravel/framework v4.2.0
    - Installation request for laravel/framework 4.2.\* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by bbrink68** [comment]
Hello,
I've updated the package tags.  For Laravel 4.2 version:

```
"mattbrown/laracurl": "1.0.0"
```
