### ISSUE TITLE
undefined method [package]

### ISSUE THREAD

**Issue by fan1200** [bbrink68/Laracurl#4]
When trying your package in Laravel 5 it gives me the following error, "Call to undefined method [package]".

I figured out that this problem is caused by the boot method in your service provider. You can solve this problem by deleting the statement in the boot method.

Don't know why the statement is there, by my believe it has something to do with Laravel 4.

Any how, just wanted you to know this. After the removal of the statement, your package works just fine :D

**Comment by bbrink68** [comment]
Which version are you using?  Are you using the correct [L5 Version](https://github.com/bbrink68/Laracurl/tree/2.0.0)?

**Comment by Riesjart2** [comment]
Same problem here, using 2.0.0 on L5.

**Comment by bbrink68** [comment]
Sorry, removed this from the 2.0.0 tagged version for L5.
